import { useState } from "react";
import { 
  useGetVehicleCostReport, 
  useExportVehicleCostReport,
  getExportVehicleCostReportQueryKey
} from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Download, BarChart3, TrendingUp, TrendingDown } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export default function Reports() {
  const { toast } = useToast();
  
  const { data: reportRows, isLoading } = useGetVehicleCostReport();
  
  // Actually, useExportVehicleCostReport is a hook generated by Orval.
  // It returns { data } typically. For a file download, we use the hook to trigger the fetch or do it imperatively.
  // Since it's a GET, it executes automatically unless disabled. Let's execute it on demand by refetching.
  const { refetch: fetchExport, isFetching: isExporting } = useExportVehicleCostReport({
    query: {
      enabled: false, // Don't fetch on mount
      queryKey: getExportVehicleCostReportQueryKey(),
    }
  });

  const handleExport = async () => {
    try {
      const result = await fetchExport();
      if (result.data) {
        // Assume result.data is the CSV string
        const blob = new Blob([result.data as any], { type: 'text/csv' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `vehicle-cost-report-${new Date().toISOString().split('T')[0]}.csv`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
        toast({ title: "Export downloaded successfully" });
      }
    } catch (err) {
      toast({ title: "Export Failed", description: "Could not generate CSV", variant: "destructive" });
    }
  };

  const totals = reportRows?.reduce((acc, row) => ({
    revenue: acc.revenue + row.revenue,
    cost: acc.cost + row.totalOperationalCost,
    distance: acc.distance + row.totalDistance,
  }), { revenue: 0, cost: 0, distance: 0 });

  return (
    <div className="flex-1 space-y-6">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">Reports & Analytics</h2>
          <p className="text-muted-foreground">Financial performance and vehicle operational costs.</p>
        </div>
        <Button onClick={handleExport} disabled={isExporting} variant="outline" className="bg-white">
          <Download className="mr-2 h-4 w-4" /> 
          {isExporting ? "Exporting..." : "Export CSV"}
        </Button>
      </div>

      {totals && (
        <div className="grid gap-4 md:grid-cols-3">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Total Fleet Revenue</CardTitle>
              <TrendingUp className="h-4 w-4 text-green-500" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-green-600">${totals.revenue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Total Operational Cost</CardTitle>
              <TrendingDown className="h-4 w-4 text-red-500" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold text-red-600">${totals.cost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">Total Distance</CardTitle>
              <BarChart3 className="h-4 w-4 text-blue-500" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">{totals.distance.toLocaleString()} km</div>
            </CardContent>
          </Card>
        </div>
      )}

      <Card>
        <CardHeader>
          <CardTitle>Vehicle Cost Report</CardTitle>
          <CardDescription>Breakdown of expenses, efficiency, and ROI per vehicle.</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Vehicle Reg.</TableHead>
                  <TableHead className="text-right">Distance</TableHead>
                  <TableHead className="text-right">Efficiency (km/L)</TableHead>
                  <TableHead className="text-right">Fuel Cost</TableHead>
                  <TableHead className="text-right">Maint. Cost</TableHead>
                  <TableHead className="text-right">Other Exp.</TableHead>
                  <TableHead className="text-right">Total Cost</TableHead>
                  <TableHead className="text-right">Revenue</TableHead>
                  <TableHead className="text-right">ROI</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {isLoading ? (
                  <TableRow><TableCell colSpan={9} className="text-center py-8 text-muted-foreground">Generating report...</TableCell></TableRow>
                ) : !reportRows || reportRows.length === 0 ? (
                  <TableRow><TableCell colSpan={9} className="text-center py-8 text-muted-foreground">No data available for report.</TableCell></TableRow>
                ) : (
                  reportRows.map((row) => (
                    <TableRow key={row.vehicleId}>
                      <TableCell className="font-medium font-mono">{row.registrationNumber}</TableCell>
                      <TableCell className="text-right">{row.totalDistance.toLocaleString()} km</TableCell>
                      <TableCell className="text-right">{row.fuelEfficiency?.toFixed(2) || "-"}</TableCell>
                      <TableCell className="text-right text-muted-foreground">${row.fuelCost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</TableCell>
                      <TableCell className="text-right text-muted-foreground">${row.maintenanceCost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</TableCell>
                      <TableCell className="text-right text-muted-foreground">${row.expenseCost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</TableCell>
                      <TableCell className="text-right font-semibold">${row.totalOperationalCost.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</TableCell>
                      <TableCell className="text-right font-semibold text-green-600">${row.revenue.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</TableCell>
                      <TableCell className="text-right">
                        <span className={`font-bold ${row.roi && row.roi >= 0 ? 'text-green-600' : 'text-red-600'}`}>
                          {row.roi ? `${row.roi > 0 ? '+' : ''}${row.roi.toFixed(1)}%` : "-"}
                        </span>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
